run:
  timeout: 3m
linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - gofumpt
    - revive
    - errcheck

linters-settings:
  revive:
    rules:
      # Disable package comment requirement
      - name: package-comments
        disabled: true
      
      # Disable exported function/type comment requirement
      - name: exported
        disabled: true
      
      # Allow blank imports with comments
      - name: blank-imports
        disabled: true

issues:
  exclude-use-default: false
